/*
 * Spring Boot Rest Server API
 * Made by olokos for purposes of recruitment to ING
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: olokos@wp.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.EntityModelVehicleEntity;

/**
 * PagedModelEntityModelVehicleEntityEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PagedModelEntityModelVehicleEntityEmbedded {
  public static final String SERIALIZED_NAME_VEHICLE_ENTITIES = "vehicleEntities";
  @SerializedName(SERIALIZED_NAME_VEHICLE_ENTITIES)
  private List<EntityModelVehicleEntity> vehicleEntities = null;

  public PagedModelEntityModelVehicleEntityEmbedded() { 
  }

  public PagedModelEntityModelVehicleEntityEmbedded vehicleEntities(List<EntityModelVehicleEntity> vehicleEntities) {
    
    this.vehicleEntities = vehicleEntities;
    return this;
  }

  public PagedModelEntityModelVehicleEntityEmbedded addVehicleEntitiesItem(EntityModelVehicleEntity vehicleEntitiesItem) {
    if (this.vehicleEntities == null) {
      this.vehicleEntities = new ArrayList<EntityModelVehicleEntity>();
    }
    this.vehicleEntities.add(vehicleEntitiesItem);
    return this;
  }

   /**
   * Get vehicleEntities
   * @return vehicleEntities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<EntityModelVehicleEntity> getVehicleEntities() {
    return vehicleEntities;
  }


  public void setVehicleEntities(List<EntityModelVehicleEntity> vehicleEntities) {
    this.vehicleEntities = vehicleEntities;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelEntityModelVehicleEntityEmbedded pagedModelEntityModelVehicleEntityEmbedded = (PagedModelEntityModelVehicleEntityEmbedded) o;
    return Objects.equals(this.vehicleEntities, pagedModelEntityModelVehicleEntityEmbedded.vehicleEntities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vehicleEntities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelEntityModelVehicleEntityEmbedded {\n");
    sb.append("    vehicleEntities: ").append(toIndentedString(vehicleEntities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

