/*
 * Spring Boot Rest Server API
 * Made by Aleksander Kos for purposes of recruitment to ING
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: olokos@wp.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VehicleEntityRequestBody
 */
public class VehicleEntityRequestBodyTest {
    private final VehicleEntityRequestBody model = new VehicleEntityRequestBody();

    /**
     * Model tests for VehicleEntityRequestBody
     */
    @Test
    public void testVehicleEntityRequestBody() {
        // TODO: test VehicleEntityRequestBody
    }

    /**
     * Test the property 'vehicleId'
     */
    @Test
    public void vehicleIdTest() {
        // TODO: test vehicleId
    }

    /**
     * Test the property 'make'
     */
    @Test
    public void makeTest() {
        // TODO: test make
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'numberPlate'
     */
    @Test
    public void numberPlateTest() {
        // TODO: test numberPlate
    }

    /**
     * Test the property 'purchasedFor'
     */
    @Test
    public void purchasedForTest() {
        // TODO: test purchasedFor
    }

    /**
     * Test the property 'vehicleTypeEnum'
     */
    @Test
    public void vehicleTypeEnumTest() {
        // TODO: test vehicleTypeEnum
    }

}
